# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(max_length=100)),
                ('atime', models.DateTimeField(auto_now_add=True)),
                ('aliulan', models.IntegerField(default=0)),
                ('aimage', models.ImageField(upload_to='booktest')),
                ('acontent', models.CharField(max_length=3000)),
                ('atop', models.BooleanField(default=False)),
                ('abupdate_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=20)),
                ('burl', models.CharField(max_length=512)),
                ('bimage', models.ImageField(upload_to='booktst/')),
                ('bindex', models.IntegerField()),
                ('bcreate_time', models.DateTimeField(auto_now_add=True)),
                ('bupdate_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='biaoqian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pinglun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pcontent', models.CharField(max_length=100)),
                ('purl', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('bcreate_time', models.DateTimeField(auto_now_add=True)),
                ('bupdate_time', models.DateTimeField(auto_now=True)),
                ('apinglun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.Article')),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='abiao',
            field=models.ManyToManyField(to='booktest.biaoqian'),
        ),
        migrations.AddField(
            model_name='article',
            name='alei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.type'),
        ),
    ]
