# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='biaoqian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='daohang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtitle', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='fabu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftitle', models.CharField(max_length=100)),
                ('fneirong', models.CharField(max_length=500)),
                ('fname', models.CharField(max_length=20)),
                ('fyuedu', models.IntegerField(default=0)),
                ('fpinglun', models.IntegerField(default=0)),
                ('fdate', models.DateField()),
                ('ftupian', models.ImageField(upload_to='booktest/')),
                ('fbq', models.ManyToManyField(to='booktest.biaoqian')),
            ],
        ),
        migrations.CreateModel(
            name='lunbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=20)),
                ('limage', models.ImageField(upload_to='booktest/')),
                ('lurl', models.CharField(max_length=512)),
            ],
        ),
    ]
