# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunbo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
