# Generated by Django 2.1.5 on 2019-01-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShuangSeQiu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hong', models.CharField(max_length=50)),
                ('lan', models.CharField(max_length=50)),
                ('times', models.CharField(max_length=50)),
            ],
        ),
    ]
