# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('nickname', models.CharField(max_length=20)),
                ('gender', models.BooleanField(default=True)),
                ('head', models.ImageField(upload_to='booktest/')),
                ('isDelete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='index',
        ),
    ]
