# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-31 08:31
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('read_num', models.IntegerField(default=0)),
                ('top', models.BooleanField(default=False)),
                ('isDelete', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '文章标题',
                'verbose_name_plural': '文章标题',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='smile/')),
                ('read_num', models.IntegerField(default=0)),
                ('top', models.BooleanField(default=False)),
                ('isDelete', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '图片标题',
                'verbose_name_plural': '图片标题',
            },
        ),
    ]
