# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-17 07:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dizhiname', models.CharField(max_length=256)),
                ('dizhimoren', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.CharField(max_length=30)),
                ('jieshao', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yifuname', models.CharField(max_length=56)),
                ('yifuprice', models.FloatField()),
                ('yifunum', models.CharField(max_length=10)),
                ('yifuurl', models.CharField(max_length=256)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ClothesAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='user.Attribute')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Clothes')),
                ('size', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='user.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Shopcar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=56)),
                ('carsize', models.CharField(max_length=10)),
                ('carnum', models.CharField(max_length=10)),
                ('carurl', models.CharField(max_length=256)),
                ('carxuan', models.IntegerField(default=0)),
                ('carprice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.IntegerField(choices=[(1, 'VIP'), (2, '普通用户')], default=2)),
                ('password', models.CharField(max_length=15)),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1)),
                ('birthday', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='shopcar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
