# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='daohang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtitle', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='lei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='mingpian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mwangm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='wenzhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wtitle', models.CharField(max_length=50)),
                ('wneirong', models.CharField(max_length=300)),
                ('wdate', models.DateField()),
                ('wpinglun', models.IntegerField(default=0)),
                ('wdianzan', models.IntegerField(default=0)),
                ('wenlei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.lei')),
            ],
        ),
    ]
