# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tupian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20)),
                ('timage', models.ImageField(upload_to='booktest/')),
                ('url', models.CharField(max_length=512)),
            ],
        ),
    ]
