# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_tupian'),
    ]

    operations = [
        migrations.AddField(
            model_name='wenzhang',
            name='wimage',
            field=models.ImageField(default='booktest/mm.jpg', upload_to='booktest/'),
            preserve_default=False,
        ),
    ]
