# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_zhangje'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhangje',
            name='xiaozhai',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booktest.Article'),
            preserve_default=False,
        ),
    ]
