# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 12:36
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True



    operations = [



    ]
