# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xiangxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xtitle', models.CharField(max_length=100)),
                ('xname', models.CharField(max_length=20)),
                ('shijie', models.CharField(max_length=20)),
                ('xdate', models.DateTimeField()),
            ],
        ),
    ]
