# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-23 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('url', models.CharField(max_length=256)),
                ('tese', models.CharField(max_length=56)),
                ('lishu', models.CharField(max_length=56)),
                ('suozaidi', models.CharField(max_length=56)),
                ('yuanshi', models.CharField(max_length=56)),
                ('boshi', models.CharField(max_length=56)),
                ('shuoshi', models.CharField(max_length=56)),
                ('address', models.CharField(max_length=126)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('wangzhi', models.CharField(max_length=256)),
                ('jianjie', models.TextField()),
                ('xingzhi', models.CharField(max_length=30)),
                ('leixing', models.CharField(max_length=20)),
            ],
        ),
    ]
